JuliaORNL/JACC.jl

.github/workflows/ci-cpu.yaml
ext/JACCCUDA/JACCCUDA.jl
src/JACC.jl
test/tests_threads_perf.jl

Test threads back end on GitHub Actions
Use Linux and macOS runners

Add CPU Threads CI

---

src/JACC.jl

Add static qualifier to threads

---

.github/workflows/ci-gpu-ornl.yaml
test/runtests.jl

Add arg option for performance tests

---

.github/workflows/ci-gpu-amd-ornl.yaml
.github/workflows/ci-gpu-nvidia-ornl.yaml
test/tests_amdgpu.jl

Add AMD GPU CI on ExCL cousteau

---

.github/workflows/ci-cpu.yaml
.github/workflows/ci-gpu-AMD.yaml
.github/workflows/ci-gpu-NVIDIA.yaml
ext/JACCAMDGPU/JACCAMDGPU.jl
test/runtests.jl

Add 4 cores in GitHub Actions tests
Remove performance tests
Remove AMDGPU sync calls

Refactor CI and address AMD sync issue

---

.github/workflows/ci-cpu.yaml
src/JACC.jl
src/helper.jl

Separate single threaded for multi-threaded code
Add single CPU thread tests on GitHub Actions
Fixes #50

Introduce maybe_threaded

---

Project.toml

v0.0.2 in Project.toml

---

ext/JACCAMDGPU/JACCAMDGPU.jl

Fixed some bugs on AMDGPU backend regarding synchronization and use of shared memory.

Fixed some bugs on AMDGPU backend regarding synchronization and use of shared memory.

---

ext/JACCAMDGPU/JACCAMDGPU.jl
test/tests_amdgpu.jl

Fix number in gridsize to match blocks, synchronize now works.
Add two unit tests
Fixes #63

Fix AMDGPU

---

.JuliaFormatter.toml
ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCONEAPI/JACCONEAPI.jl
src/JACC.jl
src/JACCPreferences.jl
src/helper.jl
test/runtests.jl
test/tests_amdgpu.jl
test/tests_amdgpu_perf.jl
test/tests_cuda.jl
test/tests_cuda_perf.jl
test/tests_oneapi.jl
test/tests_threads.jl
test/tests_threads_perf.jl

Add proper .JuliaFormatter.toml

Formatting

---

ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCAMDGPU/array.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCCUDA/array.jl
src/JACC.jl
src/array.jl
test/tests_amdgpu.jl
test/tests_cuda.jl
test/tests_threads.jl

JACC maps to the zeros and ones of each back end for array creation
Add tests
Add array.jl files for array specific function creation
Fixes #72

Support zeros and ones convenience functions

---

ext/JACCAMDGPU/array.jl
ext/JACCCUDA/array.jl
src/array.jl
test/tests_amdgpu.jl
test/tests_cuda.jl
test/tests_threads.jl

Reduce non-portable functionality to minimize potential issues

Remove non-portable zeros and ones

---

ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCONEAPI/JACCONEAPI.jl
src/JACC.jl
test/tests_amdgpu.jl
test/tests_cuda.jl
test/tests_threads.jl

Swap indices in 2D as well. 
Fixes #101

Add 3D parallel_for

---

ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCONEAPI/JACCONEAPI.jl

Added range checks to parallel_for implementations

---

ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCAMDGPU/JACCEXPERIMENTAL.jl
ext/JACCAMDGPU/JACCMULTI.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCCUDA/JACCEXPERIMENTAL.jl
ext/JACCCUDA/JACCMULTI.jl
ext/JACCONEAPI/JACCEXPERIMENTAL.jl
ext/JACCONEAPI/JACCONEAPI.jl
src/JACC.jl
src/JACCBLAS.jl
src/JACCEXPERIMENTAL.jl
src/JACCMULTI.jl
test/tests_amdgpu.jl
test/tests_cuda.jl
test/unittests.jl

Capitalized modules Multi and Experimental and applied formatting

---

.JuliaFormatter.toml
ext/JACCAMDGPU/JACCAMDGPU.jl
ext/JACCCUDA/JACCCUDA.jl
ext/JACCONEAPI/JACCONEAPI.jl
ext/JACCONEAPI/array.jl
src/JACC.jl
src/array.jl
test/JACCTests.jl
test/Project.toml
test/runtests.jl
test/tests_amdgpu.jl
test/tests_cuda.jl
test/tests_oneapi.jl
test/tests_threads.jl
test/unittests.jl

Addresses #139, #140. Partially addresses #133. See #97. Tests pass on "clark"

Update oneAPI testing

---

.github/workflows/ci-gpu-AMD.yaml
Project.toml
test/runtests.jl

Bump AMDGPU CI version

---

ext/JACCAMDGPU/JACCAMDGPU.jl
test/unittests.jl

WIP: AMDGPU compute occupancy

---

ext/JACCCUDA/JACCCUDA.jl
test/unittests.jl

Updates PRs #76 and #100
Addresses #57 and #58

WIP: Better blocks/threads calculations for CUDA backend

---

ext/JACCAMDGPU/JACCAMDGPU.jl

This follows the changes made to the CUDA.jl implementation in #136.

Use computed occupancy for amdgpu parallel_reduce

---

Project.toml
src/JACCPreferences.jl
src/helper.jl
test/runtests.jl

Install backend on `set_backend`

---

ext/AMDGPUExt/AMDGPUExt.jl
ext/AMDGPUExt/multi.jl
ext/CUDAExt/CUDAExt.jl
ext/oneAPIExt/oneAPIExt.jl

Replaced while loops in reduce kernels

---

ext/AMDGPUExt/AMDGPUExt.jl
ext/CUDAExt/CUDAExt.jl

This fixes #223 while also increasing utilization.

Better occupancy for 2D parallel_for and prevent oversubscription

---

ext/AMDGPUExt/AMDGPUExt.jl
ext/AMDGPUExt/multi.jl
ext/CUDAExt/CUDAExt.jl
ext/CUDAExt/multi.jl
ext/oneAPIExt/oneAPIExt.jl
src/JACC.jl
src/multi.jl
src/threads/multi.jl
src/threads/threads.jl
test/unittests.jl

Implements #221 and adds tests for JACC.Multi functions

JACC.Multi API updates

---

src/JACC.jl
src/multi.jl
test/unittests.jl

Added API functions for do-style syntax

---

src/threads/threads.jl
test/unittests.jl

Scope synchronize properly for threads

---

src/JACC.jl
test/unittests.jl

Refactor parallel_reduce for do syntax

---

ext/AMDGPUExt/AMDGPUExt.jl

Add missing `synchronize` implementation

---

Project.toml
src/JACC.jl
src/preferences.jl
src/threads/threads.jl
test/unittests.jl

Improvements to "threads" backend

---

ext/CUDAExt/CUDAExt.jl
ext/oneAPIExt/oneAPIExt.jl

Occupancy with oneAPI
